name: Code Quality

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  code-quality:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Vitest
        run: npm run test
      - name: Lint
        run: npm run lint
        continue-on-error: true
      - name: Prettier
        run: npm run format:check
        continue-on-error: true
